// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `CreateReminder`. */
export interface ICreateReminderResult {
}

/** Result of query `ListUserReminders`. */
export interface IListUserRemindersResult {
    id: IReminderColumns["id"];
    user_id: IReminderColumns["user_id"];
    chat_id: IReminderColumns["chat_id"];
    text: IReminderColumns["text"];
    due_at: IReminderColumns["due_at"];
    sent_at: IReminderColumns["sent_at"];
    created_at: IReminderColumns["created_at"];
}

/** Result of query `DeleteUserReminder`. */
export interface IDeleteUserReminderResult {
    id: IReminderColumns["id"];
}

/** Result of query `ListDueReminders`. */
export interface IListDueRemindersResult {
    id: IReminderColumns["id"];
    user_id: IReminderColumns["user_id"];
    chat_id: IReminderColumns["chat_id"];
    text: IReminderColumns["text"];
    due_at: IReminderColumns["due_at"];
    sent_at: IReminderColumns["sent_at"];
    created_at: IReminderColumns["created_at"];
}

/** Result of query `MarkReminderSent`. */
export interface IMarkReminderSentResult {
    id: IReminderColumns["id"];
}

/** Result of query `ReadBotSession`. */
export interface IReadBotSessionResult {
    value: IBotSessionColumns["value"];
}

/** Result of query `WriteBotSession`. */
export interface IWriteBotSessionResult {
}

/** Result of query `DeleteBotSession`. */
export interface IDeleteBotSessionResult {
}

/** Result of query `UpsertTelegramUser`. */
export interface IUpsertTelegramUserResult {
}

export interface Queries {
    CreateReminder: ICreateReminderResult;
    ListUserReminders: IListUserRemindersResult;
    DeleteUserReminder: IDeleteUserReminderResult;
    ListDueReminders: IListDueRemindersResult;
    MarkReminderSent: IMarkReminderSentResult;
    ReadBotSession: IReadBotSessionResult;
    WriteBotSession: IWriteBotSessionResult;
    DeleteBotSession: IDeleteBotSessionResult;
    UpsertTelegramUser: IUpsertTelegramUserResult;
}

/** Columns of `bot_session`. */
export interface IBotSessionColumns {
    key: string;
    value: string;
    updated_at: string;
}

/** Schema of `bot_session`. */
export interface IBotSessionTable {
    columns: IBotSessionColumns;
    relationType: (typeof schema)["bot_session"]["_relationType"];
    indexes: keyof (typeof schema)["bot_session"]["_indexes"];
    constraints: keyof (typeof schema)["bot_session"]["_constraints"];
}

/** Columns of `reminder`. */
export interface IReminderColumns {
    id: string;
    user_id: string;
    chat_id: string;
    text: string;
    due_at: string;
    sent_at: string | null;
    created_at: string;
}

/** Schema of `reminder`. */
export interface IReminderTable {
    columns: IReminderColumns;
    relationType: (typeof schema)["reminder"]["_relationType"];
    indexes: keyof (typeof schema)["reminder"]["_indexes"];
    constraints: keyof (typeof schema)["reminder"]["_constraints"];
}

/** Columns of `telegram_user`. */
export interface ITelegramUserColumns {
    id: string;
    username: string | null;
    first_name: string | null;
    last_name: string | null;
    language_code: string | null;
    created_at: string;
    updated_at: string;
}

/** Schema of `telegram_user`. */
export interface ITelegramUserTable {
    columns: ITelegramUserColumns;
    relationType: (typeof schema)["telegram_user"]["_relationType"];
    indexes: keyof (typeof schema)["telegram_user"]["_indexes"];
    constraints: keyof (typeof schema)["telegram_user"]["_constraints"];
}

export const schema = {
    bot_session: {
        _relationName: "bot_session",
        _relationType: "table",
        _columns: {
            key: { _columnName: "key", _foreignKeys: {} },
            value: { _columnName: "value", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} }
        },
        _indexes: {
            sqlite_autoindex_bot_session_1: { _indexName: "sqlite_autoindex_bot_session_1" }
        },
        _constraints: {}
    },
    reminder: {
        _relationName: "reminder",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            user_id: { _columnName: "user_id", _foreignKeys: {} },
            chat_id: { _columnName: "chat_id", _foreignKeys: {} },
            text: { _columnName: "text", _foreignKeys: {} },
            due_at: { _columnName: "due_at", _foreignKeys: {} },
            sent_at: { _columnName: "sent_at", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} }
        },
        _indexes: {
            reminder_due_unsent_idx: { _indexName: "reminder_due_unsent_idx" },
            reminder_owner_due_idx: { _indexName: "reminder_owner_due_idx" },
            sqlite_autoindex_reminder_1: { _indexName: "sqlite_autoindex_reminder_1" }
        },
        _constraints: {}
    },
    telegram_user: {
        _relationName: "telegram_user",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            username: { _columnName: "username", _foreignKeys: {} },
            first_name: { _columnName: "first_name", _foreignKeys: {} },
            last_name: { _columnName: "last_name", _foreignKeys: {} },
            language_code: { _columnName: "language_code", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} }
        },
        _indexes: {
            sqlite_autoindex_telegram_user_1: { _indexName: "sqlite_autoindex_telegram_user_1" }
        },
        _constraints: {}
    }
} as const;

export interface Tables {
    bot_session: IBotSessionTable;
    reminder: IReminderTable;
    telegram_user: ITelegramUserTable;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
